USE `netland`;
 create table `Films` (
	ID MEDIUMINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    Title VARCHAR(100) NOT NULL,
    Duur VARCHAR(100 ) NOT NULL,
 Uitkomst_Datum  TEXT NOT NULL,
 Omschrijving TEXT NOT NULL,
Land_van_Uitkomst ENUM('NL', 'UK','US') NOT NULL,
 YouTube_Trailer  TEXT NOT NULL
 );
 insert into `Films` (`Title`,`Duur`,`Uitkomst_Datum`,`Omschrijving`,`Land_van_Uitkomst`,`YouTube_Trailer`) VALUES 
 ('A Quiet Place: Part II', '1 u 40 m', '8 maart 2020', 'A Quiet Place Part II is een toekomstige Amerikaanse horrorfilm geregisseerd en geschreven door John Krasinski en is het vervolg op A Quiet Place uit 2017. Emily Blunt, Millicent Simmonds, Noah Jupe en John Krasinski keren terug als de hoofdpersonages uit het eerste deel. Het verhaal borduurt zich verder waar het eerste deel is geëindigd. De familie Abbott verlaat het ouderlijk huis en gaan verder met hun zoektocht waar nog enig teken van leven is. Echter moeten zij dit in stilte doen, aangezien de wezens die op geluid afkomen niet het enige gevaar zijn.','US','https://youtu.be/a9lGyL7Oask'),
 ('Onward','1 u 42 m','4 maart 2020','Onward is een Amerikaanse, digitale animatiefilm uit 2020 die geschreven en geregisseerd werd door Dan Scanlon en geproduceerd door Pixar Animation Studios voor Walt Disney Pictures. De film speelt zich af in een voorstedelijke fantasiewereld, bewoond door elfen, trollen, zeemeerminnen, centauren, kabouters, faunen en eenhoorns. Twee tienerelfen onderzoeken of er nog steeds magie bestaat die hun vader terug kan brengen uit de dood.','US','https://youtu.be/4eXuPJbQclQ'),
  ('Mulan','2 uur','26 maart 2020','Mulan is een Amerikaanse film uit 2020 onder regie van Niki Caro. Het is een remake van de Disney-animatiefilm Mulan uit 1998. De première vond plaats in Los Angeles op 9 maart 2020. De bioscooprelease is echter door de uitbraak van het coronavirus uitgesteld tot een nader te bepalen datum.De film speelt zich af in China, tijdens de Han-dynastie. Fa Mulan, dochter van de oude oorlogsveteraan Fa Zhou, doet zich voor als mannelijke soldaat, om zo de plaats van haar vader in te nemen in het gevecht tegen een invasie van de Hunnen.','US','https://youtu.be/GrAB73uknuY'),
   ('Soul','-','17 juni 2020','Soul is een Amerikaanse toekomstige computeranimatiefilm, geregisseerd door Pete Docter en geproduceerd door Pixar Animation Studios in samenwerking met Walt Disney Animation Studios.Joe Gardner is een muziekleraar op de middelbare school die er van droomt als jazzmuzikant op het podium te staan. Op een avond krijgt hij eindelijk de kans op te treden als openingsact in de Half Note Club. Door een ongeluk wordt zijn ziel echter gescheiden van zijn lichaam en getransporteerd naar het You Seminar, een centrum waar zielen zich ontwikkelen vooraleer ze naar een pasgeboren kind worden getransporteerd. Gardner moet samenwerken met zielen in training zoals 22, een ziel met een vage kijk op het leven die al jarenlang op het seminarie zit, om terug te kunnen keren naar Aarde voordat het te laat is.','US','https://youtu.be/4TojlZYqPUo'),
    ('Sonic the Hedgehog','1 u 40 m','12 februari 2020','Sonic the Hedgehog is een Amerikaans-Japanse komische avonturenfilm uit 2020, gebaseerd op de gelijknamige computerspelserie van Sega. De film werd geregisseerd door Jeff Fowler, naar een scenario door Patrick Casey en Josh Miller.Sonic is een antropomorfe blauwe egel van de planeet Mobius, die naar de aarde vlucht. Schurken willen Sonics supersnelheid zien te bemachtigen voor hun eigen gewin. Nadat Sonic per ongeluk een stroomuitval veroorzaakt in het dorpje Green Hills, wordt hij gezocht door de overheid die de kwaadaardige Doctor Robotnik inhuurt om hem op te sporen. Sheriff Tom Wachowski moet Sonic helpen om zijn ringen terug te verzamelen en om uit de handen van Robotnik te blijven.','US','https://youtu.be/SzXA5emZQs8'),
	('Onze Jongens in Miami',' 1 u 50 m','30 januari 2020','In Onze jongens in Miami is Jorrit (Jim Bakkum) weer single en gaat hij samen met Bas (Martijn Fischer) een stripclub openen in Miami. Uiteraard vliegt ook Thijs (Juvat Westendorp) naar Miami samen met nieuwe stripper en collega-bouwvakker Boris (Malik Mohammed). Ze moeten flink aan de bak want de club blijkt een enorme bouwval en de mannen komen er al snel achter dat ze te maken hebben met stevige concurrentie.','NL','https://youtu.be/lfTzvePLReU');
SELECT * FROM Films;
SHOW TABLES;
DESCRIBE Films;